# Generated by Django 6.0.6 on 2026-06-20 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrower', '0001_initial'),
        ('item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lent_at', models.DateTimeField(help_text='Fecha y hora en que se prestó el ítem')),
                ('due_at', models.DateTimeField(help_text='Fecha y hora en que se debe devolver el ítem')),
                ('returned_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se devolvió el ítem (opcional)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Ingrese notas adicionales sobre el préstamo (opcional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='borrower.borrower')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='item.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'préstamo',
                'verbose_name_plural': 'préstamos',
            },
        ),
        migrations.CreateModel(
            name='LoanPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Suba una foto del ítem prestado (opcional)', upload_to='loan_photos/')),
                ('moment', models.CharField(choices=[('lent', 'Al prestar'), ('returned', 'Al devolver')], help_text='Seleccione el momento en que se tomó la foto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='loan.loan')),
            ],
            options={
                'verbose_name': 'foto de préstamo',
                'verbose_name_plural': 'fotos de préstamos',
            },
        ),
    ]
